name: mechanics-${SERVICE_NAME?}

services:
  dotnet:
    build: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - EmailSenderOptions__SmtpServer=mailpit
      - AwsCredentials__LocalstackUrl=http://localstack:4566
      - CrossServiceClients__IdentityBaseUrl=${IDENTITY?}
      - CrossServiceClients__WorkOrdersBaseUrl=${WORK_ORDERS?}
      - MercadoPagoOptions__AccessToken=${MERCADO_PAGO_ACCESS_TOKEN:-}
      - MercadoPagoOptions__NotificationUrl=${MERCADO_PAGO_NOTIFICATION_URL:-}
    ports:
      - "5000:8080"
    volumes:
      - dotnet:/home/app
      - ./src/Mechanics.Api/keys:/app/keys:ro
    depends_on:
      mailpit:
        condition: service_healthy
      localstack:
        condition: service_healthy

  mailpit:
    image: axllent/mailpit:v1.28
    environment:
      - MP_DATABASE=/data/mailpit.db
      - MP_MAX_AGE=7d
      - TZ=America/Sao_Paulo
      - MP_SMTP_AUTH=postmaster@mechanics.com:xFCsMj6a4NWbZgr5
      - MP_SMTP_AUTH_ALLOW_INSECURE=true
    ports:
      - "1025:1025"
      - "8025:8025"
    volumes:
      - mailpit:/data
    healthcheck:
      test: 'wget --spider -q http://localhost:8025/api/v1/info'
      interval: 2s
      timeout: 5s
      retries: 10

  localstack:
    image: localstack/localstack:3
    environment:
      - SERVICES=sqs,dynamodb,lambda
      - DYNAMODB_SHARE_DB=1
      - DYNAMODB_IN_MEMORY=1
    ports:
      - "4566:4566"
    volumes:
      - ./scripts/localstack:/etc/localstack/init/ready.d:ro
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: 'curl -f http://localhost:4566/_localstack/health'
      interval: 2s
      timeout: 5s
      retries: 10

volumes:
  dotnet:
    name: mechanics-${SERVICE_NAME?}-dotnet
  mailpit:
    name: mechanics-${SERVICE_NAME?}-mailpit
