apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: {{ .Values.app.name }}-payments

spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.secrets.clusterSecretStore }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.app.name }}-payments
  data:
    - secretKey: accessToken
      remoteRef:
        key: "{{ .Values.app.project }}-{{ .Values.app.env }}-{{ .Values.secrets.paymentsCredentialsSecretName }}"
        property: accessToken
    - secretKey: notificationUrl
      remoteRef:
        key: "{{ .Values.app.project }}-{{ .Values.app.env }}-{{ .Values.secrets.paymentsUrlSecretName }}"
        property: notificationUrl
